name: mend_scan
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
      with:
        fetch-depth: 1
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    # if there's no go.sum, generate it 
    - name: check go.sum
      run: '[ -f "go.sum" ] && echo "go sum exists, skipping" || go mod tidy'
    # install java
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    # download mend
    - name: download_mend
      run: curl -o wss-unified-agent.jar https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    - name: run mend
      run: java -jar wss-unified-agent.jar
      env:
        WS_APIKEY: ${{ secrets.MEND_API_KEY }}
        WS_WSS_URL: https://saas-eu.whitesourcesoftware.com/agent
        WS_USERKEY: ${{ secrets.MEND_TOKEN }}
        WS_PRODUCTNAME: Puppet General
        WS_PROJECTNAME: ${{ github.event.repository.name }}
        WS_FILESYSTEMSCAN: true
        WS_CHECKPOLICIES: true
        WS_FORCEUPDATE: true
